apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    database: smart_city_dq
    basicAuth: false
    isDefault: true
    jsonData:
      username: default
      server: clickhouse
      port: 9000
      protocol: native
    secureJsonData:
      password: ""
